services:
  web:
    # build:
    #   context: ./
    #   target: runner
    # volumes:
    #   - .:/app
    build: .
    container_name: blog
    volumes:
      - .:/code
      - app:/home/app
      - '~/.ssh:/home/app/.ssh'
      - '~/.gitconfig:/home/app/.gitconfig'
      - '~/.gitignore:/home/app/.gitignore'
    working_dir: /code
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development

volumes:
  app: