name: build
on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: actions/checkout@v2

      - name: Build
        run: npm i && ./build.sh

      - name: deploy docs
        uses: appleboy/gh-pages-action@v0.0.2
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          remote_url: https://github.com/Laegel/blog.git
          target_branch: release
          target_directory: docs
