name: build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: denolib/setup-deno@v2

    - uses: actions/checkout@v2

    - name: Build with Aleph
      run: deno run -A https://deno.land/x/aleph/install.ts && ./build.sh

    - name: deploy docs
      uses: appleboy/gh-pages-action@v0.0.2
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        remote_url: https://github.com/Laegel/blog.git
        target_directory: docs