name: build
on: push
jobs:
  build:
    container: denoland/deno:latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build with Aleph
      run: cd app && aleph build
